import React from 'react'
import type { Metadata } from 'next'
import '@src/styles/global.css'
import { ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang='en'>
      <body className='bg-white w-[100dvw] h-[100dvh] text-black font-medium font-manrope'>
        {children}
      </body>
    </html>
  )
}
export default RootLayout
