import React from 'react'
import type { Metadata } from 'next'
import '@src/styles/global.css'
import { ReactNode } from 'react'
import { Nunito } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const nunito = Nunito({
  weight: ['200', '300', '400', '600', '700', '800', '900'],
  subsets: ['latin'],
})
const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang='en'>
      <body
        className={`${nunito.className} bg-[#F8F8FA] w-[100dvw] h-[100dvh] text-black`}
      >
        {children}
      </body>
    </html>
  )
}
export default RootLayout
